# Site settings
title: Ruby on Rails ガイド
email: yasulab@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Rails を学び，使うための公式リファレンスマニュアル
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://railsguides.jp" # the base hostname & protocol for your site
twitter_username: yasulab
github_username:  yasulab
source:      ./guides/output/ja
destination: ./_site

# Build settings
markdown: kramdown
gems:     ['kramdown']
exclude:
  - unicorn.rb
  - README.md
  - Procfile
  - Gemfile
  - Gemfile.lock
  - config.ru
  - vendor
  - app.json
